#!/bin/bash

# Auto-fix script generated by Enhanced Deployment Block Checker v3.0
# Generated: 2025-11-18T00:27:23.056Z
# Auto-fixable violations: 149
# Estimated time saved: ~5092 minutes

set -e

echo "🤖 Auto-fixing 149 violations..."
echo "⏱️  Started at: $(date)"

# Fix Environment Variables violations
if [ 37 -gt 0 ]; then
    echo ""
    echo "🔧 Fixing Environment Variables violations (37 files)..."
    
    # Replace process.env with Bun.env
    find packages/ -name "*.ts" -type f -exec sed -i '' 's/process\.env/Bun.env/g' {} \;
    
    # Remove dotenv imports
    find packages/ -name "*.ts" -type f -exec sed -i '' '/import.*dotenv/d' {} \;
    find packages/ -name "*.ts" -type f -exec sed -i '' '/import.*dotenv-expand/d' {} \;
    
    # Remove dotenv usage
    find packages/ -name "*.ts" -type f -exec sed -i '' '/dotenv\.config/d' {} \;
    find packages/ -name "*.ts" -type f -exec sed -i '' '/dotenvExpands\.config/d' {} \;
    
    echo "✅ Environment Variables fixed"
fi

# Add apiTracker imports to files with Track API Usage violations
if [ 112 -gt 0 ]; then
    echo ""
    echo "🔧 Adding apiTracker imports to 112 files..."
    
    # Get unique files that need apiTracker import
    FILES_NEEDING_TRACKER=$(echo "/Users/nolarose/CascadeProjects/windsurf-project/mcp-server/bun-mcp-server.ts
/Users/nolarose/CascadeProjects/windsurf-project/mcp-server/bun-mcp-server.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/pre-commit-validate.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/core/preload.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/core/preload.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/core/build.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/test/run-all-tests.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/test/test-setup.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/test/continuous-testing.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/test/continuous-testing.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/incremental-verification.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/incremental-verification.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/incremental-verification.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/incremental-verification.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/incremental-verification.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/setup/automated-setup.ts
/Users/nolarose/CascadeProjects/windsurf-project/scripts/generate-rule-dashboard.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-websocket/src/server-v13.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-websocket/src/server-v13.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-websocket/src/bun-v13-server.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-websocket/src/bun-v13-server.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-official-docs-compliance.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/tests/bun-utilities-showcase.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-complete-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-complete-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-complete-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/__tests__/integration.test.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-native-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-native-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-native-apis.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts
/Users/nolarose/CascadeProjects/windsurf-project/packages/odds-core/src/bun-utils.ts" | sort -u)
    
    for file in $FILES_NEEDING_TRACKER; do
        if [ -f "$file" ]; then
            # Check if apiTracker import already exists
            if ! grep -q "apiTracker" "$file"; then
                # Determine correct import path based on file location
                if [[ "$file" == packages/odds-core/* ]]; then
                    IMPORT_PATH="'./monitoring/api-tracker.js'"
                elif [[ "$file" == packages/odds-websocket/* ]]; then
                    IMPORT_PATH="'odds-core/src/monitoring/api-tracker.js'"
                elif [[ "$file" == scripts/* ]]; then
                    IMPORT_PATH="'../packages/odds-core/src/monitoring/api-tracker.js'"
                else
                    IMPORT_PATH="'../packages/odds-core/src/monitoring/api-tracker.js'"
                fi
                
                # Add import after the first import line
                sed -i '' "1a\
import { apiTracker } from $IMPORT_PATH;" "$file"
                echo "  ✅ Added apiTracker import to $file"
            fi
        fi
    done
    
    echo "✅ apiTracker imports added"
fi

echo ""
echo "🎯 Auto-fix completed!"
echo "📊 Fixed: 149 violations"
echo "⏱️  Completed at: $(date)"
echo ""
echo "🔄 Next steps:"
echo "1. Run: bun run rules:block"
echo "2. Manually fix remaining violations"
echo "3. Commit and test changes"
