// examples/testing/regressions/test-regression-http-001-http-client.test.ts
// Regression test for HTTP Client Operations
// Issue: http-001
// Category: http-client
// Description: Ensure fetch() and HTTP client operations work correctly
// Generated by regression test generator

import { describe, test, expect } from "bun:test";

describe("Regression: HTTP Client Operations", () => {
  test("basic fetch GET", async () => {
    // Test basic fetch GET request
    // Use httpbin.org for testing
    const response = await fetch("https://httpbin.org/get");
    const data = await response.json();
    var hasUrl = "url" in data;
    expect(hasUrl).toBe(true);
  });

  test("fetch with headers", async () => {
    // Test fetch with custom headers
    const response = await fetch("https://httpbin.org/headers", {
      headers: {
        "X-Test-Header": "test-value",
        "User-Agent": "Bun-Test/1.0"
      }
    });
    const data = await response.json();
    var hasTestHeader = data.headers["X-Test-Header"] === "test-value";
    expect(hasTestHeader).toBe(true);
  });

  test("fetch POST with JSON", async () => {
    // Test fetch POST with JSON body
    const testData = { message: "test", timestamp: Date.now() };
    const response = await fetch("https://httpbin.org/post", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(testData)
    });
    const data = await response.json();
    var dataMatches = data.json.message === testData.message;
    expect(dataMatches).toBe(true);
  });
});