// examples/testing/regressions/test-regression-ws-001-websocket.test.ts
// Regression test for WebSocket Server Functionality
// Issue: ws-001
// Category: websocket
// Description: Ensure WebSocket server operations work correctly
// Generated by regression test generator

import { describe, test, expect } from "bun:test";

describe("Regression: WebSocket Server Functionality", () => {
  test("basic WebSocket connection", async () => {
    // Test basic WebSocket connection establishment
    let connectionCount = 0;
    const server = Bun.serve({
      port: 0,
      websocket: {
        open(ws) {
          connectionCount++;
          ws.send("Hello from server");
        },
        message(ws, message) {
          ws.send(`Echo: ${message}`);
        },
      },
      fetch(req, server) {
        if (server.upgrade(req)) {
          return;
        }
        return new Response("WebSocket upgrade failed", { status: 400 });
      },
    });

    // Connect client
    const ws = new WebSocket(`ws://localhost:${server.port}/`);
    let receivedMessage = false;

    await new Promise((resolve) => {
      ws.onmessage = (event) => {
        receivedMessage = event.data === "Hello from server";
        ws.close();
        resolve(void 0);
      };
    });

    server.stop();
    expect(receivedMessage && connectionCount === 1).toBe(true);
  });

  test("WebSocket message echo", async () => {
    // Test WebSocket message echoing
    const server = Bun.serve({
      port: 0,
      websocket: {
        message(ws, message) {
          ws.send(`Echo: ${message}`);
        },
      },
      fetch(req, server) {
        if (server.upgrade(req)) {
          return;
        }
        return new Response("Upgrade failed", { status: 400 });
      },
    });

    const ws = new WebSocket(`ws://localhost:${server.port}/`);
    const testMessage = "test message";
    let echoedCorrectly = false;

    await new Promise((resolve) => {
      ws.onmessage = (event) => {
        echoedCorrectly = event.data === `Echo: ${testMessage}`;
        ws.close();
        resolve(void 0);
      };

      ws.onopen = () => {
        ws.send(testMessage);
      };
    });

    server.stop();
    expect(echoedCorrectly).toBe(true);
  });
});