// examples/testing/regressions/test-regression-serve-001-serve.test.ts
// Regression test for Bun.serve() Basic Functionality
// Issue: serve-001
// Category: serve
// Description: Ensure Bun.serve() works correctly with basic HTTP requests
// Generated by regression test generator

import { describe, test, expect } from "bun:test";

describe("Regression: Bun.serve() Basic Functionality", () => {
  test("basic GET request", async () => {
    // Test basic GET request handling
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        return new Response("Hello World");
      },
    });

    const response = await fetch(`http://localhost:${server.port}/`);
    const text = await response.text();

    server.stop();
    expect(text === "Hello World").toBe(true);
  });

  test("POST request with body", async () => {
    // Test POST request with JSON body
    const server = Bun.serve({
      port: 0,
      async fetch(req) {
        if (req.method === "POST") {
          const body = await req.json();
          return Response.json({ received: body });
        }
        return new Response("Method not allowed", { status: 405 });
      },
    });

    const response = await fetch(`http://localhost:${server.port}/`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ test: "data" }),
    });
    const data = await response.json();

    server.stop();
    expect(data.received.test === "data").toBe(true);
  });

  test("middleware functionality", async () => {
    // Test middleware-like functionality
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        // Simulate middleware
        const url = new URL(req.url);
        if (url.pathname === "/api") {
          return Response.json({ api: true });
        }
        return new Response("Not Found", { status: 404 });
      },
    });

    const response = await fetch(`http://localhost:${server.port}/api`);
    const data = await response.json();

    server.stop();
    expect(data.api === true).toBe(true);
  });
});