// examples/testing/regressions/test-regression-fs-001-filesystem.test.ts
// Regression test for File System Operations
// Issue: fs-001
// Category: filesystem
// Description: Ensure Bun.file() and file system operations work correctly
// Generated by regression test generator

import { describe, test, expect } from "bun:test";

describe("Regression: File System Operations", () => {
  test("Bun.file() text reading", async () => {
    // Test Bun.file() text reading functionality
    const testFile = Bun.file("../../README.md");
    const exists = await testFile.exists();
    if (exists) {
      const content = await testFile.text();
      var hasContent = content.length > 0;
    } else {
      var hasContent = false;
    }
    expect(hasContent).toBe(true);
  });

  test("Bun.file() TOML parsing", async () => {
    // Test Bun.file() TOML parsing
    const testFile = Bun.file("../../../bunfig.toml");
    const exists = await testFile.exists();
    if (exists) {
      const content = await testFile.text();
      var hasContent = content.length > 0;
    } else {
      var hasContent = false;
    }
    expect(hasContent).toBe(true);
  });

  test("file streaming", async () => {
    // Test file streaming capabilities
    const testFile = Bun.file("../../README.md");
    const exists = await testFile.exists();
    if (exists) {
      const stream = testFile.stream();
      const reader = stream.getReader();
      const chunk = await reader.read();
      var hasData = !chunk.done && chunk.value.length > 0;
      reader.releaseLock();
    } else {
      var hasData = false;
    }
    expect(hasData).toBe(true);
  });
});