name: Issue Labeler

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Label issues and PRs
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml